# -*- js -*-
{
  "version": 2.1,

    "jobs": {
        "build": {
            "docker": [{"image": "debian:stable"}],
            "steps": [
                "checkout",
                "apt-get update -qq",
                "apt-get install -qq cloc make git luajit2 lua5.1 lua5.2 lua5.3 lua5.4",
                "make ci",
                "git diff --quiet",
            ]
        }
    }

    "workflows": {
        "version": 2
        "all": {
            "jobs": ["build"]
        }
    }
}
